---
tomcat_user: tomcat
tomcat_home_directory: /opt/tomcat
tomcat_shell_directory: /bin/false
tomcat_url: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.65/bin/apache-tomcat-9.0.65.tar.gz
tomcat_service_file_location: /etc/systemd/system/tomcat.service
tomcat_users_file_location: /opt/tomcat/latest/conf/tomcat-users.xml
tomcat_manager_app_file_location: /opt/tomcat/latest/webapps/manager/META-INF/context.xml
tomcat_host_manager_app_file_location: /opt/tomcat/latest/webapps/host-manager/META-INF/context.xml
ansible_username: rowdy
ansible_password: boyz
all_hosts: ".*"